repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
- repo: local
  hooks:
    - id: ruff-check
      name: ruff-check
      entry: uv run ruff check
      language: system
      types: [python]
    - id: ruff-format
      name: ruff-format
      entry: uv run ruff format
      language: system
      types: [python]
