"""Office formats end to end through real LibreOffice + the real PDF ladder.

The unit tests stub the conversion, so nothing there would catch a wrong
LibreOffice argument, a missing import filter, or a rendition the PDF ladder
cannot read. These run the actual binary.

Fixtures are generated by LibreOffice itself from HTML rather than committed as
binaries, so there is nothing opaque in the tree and the legacy ``.doc``/``.xls``
cases exercise the same import filters a real document would.
"""

import pytest

from nextcloud_mcp_server.document_processors import _libreoffice
from nextcloud_mcp_server.document_processors.office import (
    RENDERED_FROM_KEY,
    OfficeDocumentProcessor,
)
from nextcloud_mcp_server.document_processors.spreadsheet import (
    SHEET_BOUNDARIES_KEY,
    XLS_MIME,
    SpreadsheetProcessor,
)

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        not _libreoffice.LIBREOFFICE_AVAILABLE,
        reason="LibreOffice (soffice) is not installed",
    ),
]

DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
DOC_MIME = "application/msword"

# A merged first cell spanning two rows: the exact shape that makes a
# mammoth/markdownify parse drop a cell and shift the rest of the row one
# column left, so answers land under the wrong heading.
TABLE_HTML = """<html><body>
<h1>Supplier Questionnaire</h1>
<p>Please complete and return this questionnaire.</p>
<table border="1">
<tr><td>Domain</td><td>Question</td><td>Answer</td></tr>
<tr><td rowspan="2">Certifications</td><td>Do you hold ISO 27001?</td><td>Yes</td></tr>
<tr><td>Do you hold Cyber Essentials?</td><td>Not applicable</td></tr>
</table>
</body></html>"""


async def _word_fixture(target_filter: str) -> bytes:
    """A real Word document, converted from HTML by LibreOffice.

    The export filter has to be named explicitly: a bare ``--convert-to docx``
    from HTML aborts with "no export filter found", because LibreOffice cannot
    tell which module should claim the input.
    """
    return await _libreoffice.convert(
        TABLE_HTML.encode(), "q.html", target_filter, timeout=180.0
    )


async def _xls_fixture() -> bytes:
    """A real legacy .xls, via xlsx -- both formats belong to Calc, so the
    conversion is unambiguous where HTML -> xls is not."""
    import io

    import openpyxl

    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "Answers"
    for row in (
        ["Domain", "Answer"],
        ["Certifications", "ISO 27001"],
        ["Testing", "Annual pen test"],
    ):
        sheet.append(row)
    buf = io.BytesIO()
    workbook.save(buf)
    return await _libreoffice.convert(buf.getvalue(), "s.xlsx", "xls", timeout=180.0)


@pytest.mark.parametrize(
    ("target_filter", "mime"),
    [("docx:MS Word 2007 XML", DOCX_MIME), ("doc:MS Word 97", DOC_MIME)],
)
async def test_word_document_is_rendered_and_parsed(target_filter, mime):
    """Both the modern and legacy Word formats reach text, pages and tables."""
    content = await _word_fixture(target_filter)
    target = "docx" if "2007" in target_filter else "doc"

    result = await OfficeDocumentProcessor(timeout=180.0).process(
        content, mime, f"q.{target}"
    )

    assert "Supplier Questionnaire" in result.text
    assert "ISO 27001" in result.text
    # The rendition is a real PDF, so page geometry comes from the existing path.
    assert len(result.metadata["page_boundaries"]) >= 1
    assert result.metadata[RENDERED_FROM_KEY] == mime
    assert result.processor == "office"


async def test_merged_cell_keeps_its_answer_in_the_answer_column():
    """The defect the rendition route exists to avoid.

    A direct mammoth parse emits three cells for the second body row where the
    header has four, shifting "Not applicable" under the question column.
    """
    content = await _word_fixture("docx:MS Word 2007 XML")

    result = await OfficeDocumentProcessor(timeout=180.0).process(
        content, DOCX_MIME, "q.docx"
    )

    rows = [ln for ln in result.text.splitlines() if ln.count("|") >= 2]
    assert rows, f"no markdown table recovered from the rendition: {result.text!r}"
    answer_rows = [r for r in rows if "Not applicable" in r]
    assert answer_rows, "the merged-cell row vanished from the table"
    # "Not applicable" must be the last populated cell, i.e. still in the Answer
    # column rather than shifted left into Question.
    cells = [c.strip() for c in answer_rows[0].strip("|").split("|")]
    assert cells[-1] == "Not applicable"


async def test_page_boundaries_index_the_returned_text_exactly():
    """The offsets the chunker and pdf_highlighter both rely on."""
    content = await _word_fixture("docx:MS Word 2007 XML")

    result = await OfficeDocumentProcessor(timeout=180.0).process(
        content, DOCX_MIME, "q.docx"
    )

    boundaries = result.metadata["page_boundaries"]
    assert boundaries[0]["start_offset"] == 0
    assert boundaries[-1]["end_offset"] == len(result.text)
    for previous, following in zip(boundaries, boundaries[1:]):
        assert previous["end_offset"] == following["start_offset"]


async def test_legacy_xls_is_read_cell_by_cell_not_paginated():
    """.xls converts container-to-container, so no cell is lost to a page break."""
    content = await _xls_fixture()

    result = await SpreadsheetProcessor(timeout=180.0).process(
        content, XLS_MIME, "s.xls"
    )

    assert "| Certifications | ISO 27001 |" in result.text
    assert "| Testing | Annual pen test |" in result.text
    assert result.metadata["converted_from_mime"] == XLS_MIME
    assert len(result.metadata[SHEET_BOUNDARIES_KEY]) >= 1
    # A spreadsheet has no page geometry, and must not pretend otherwise.
    assert "page_boundaries" not in result.metadata
