#!/bin/bash

set -euox pipefail

php /var/www/html/occ config:system:set trusted_domains 2 --value=host.docker.internal

# Set overwrite settings for URL generation (needed for OIDC discovery to return correct URLs)
# These ensure that URLs generated by Nextcloud include the correct host:port
php /var/www/html/occ config:system:set overwritehost --value="localhost:8080"
php /var/www/html/occ config:system:set overwriteprotocol --value="http"
php /var/www/html/occ config:system:set overwrite.cli.url --value="http://localhost:8080"
